apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kronos-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list","watch"]
- apiGroups: ["kronos.io"]
  resources: ["kronossecuritypolicies"]
  verbs: ["list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kronos-role-binding
subjects:
- kind: ServiceAccount
  name: kronos-sa       # 👈 Match the service account name
  namespace: default
roleRef:
  kind: ClusterRole
  name: kronos-role
  apiGroup: rbac.authorization.k8s.io
